#!/bin/bash -e
#
# Install later from source to /var/lib/later
#

if [[ $(id -u) -ne 0 ]]
then
	echo running as root
	sudo $0
	exit $?
fi

cd $(dirname $0)

test -d /var/lib/later || mkdir /var/lib/later
cp -rf * /var/lib/later/

test -h /usr/bin/later || ln -s /var/lib/later/later /usr/bin/later

